=== digorydoo/goigoi/goigoi-xml/schema/kanji_index_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        JLPT level associated with this kanji. The value "-" explicitly states the kanji is not associated with any
        particular JLPT level.
    -->
    <xs:simpleType name="JLPTLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="n5" />
            <xs:enumeration value="n4" />
            <xs:enumeration value="n3" />
            <xs:enumeration value="n2" />
            <xs:enumeration value="n1" />
            <xs:enumeration value="-" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Used to set the JLPT level or schoolyear of a list of kanjis.
    -->
    <xs:complexType name="Set">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lvl" type="JLPTLevel" />
                <xs:attribute name="schoolyear" type="xs:int" />
                <xs:attribute name="rem" type="xs:string" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!--
        Marks groups of kanjis as visually similar.
    -->
    <xs:complexType name="VisuallySimilar">
        <xs:sequence>
            <xs:element name="group" type="VisuallySimilarGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!--
        One group of visually similar kanjis.
    -->
    <xs:simpleType name="VisuallySimilarGroup">
        <xs:restriction base="xs:string">
            <xs:minLength value="2" />
            <xs:maxLength value="5" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Marks the list of kanjis as occurring in the frequency in the order as they appear here in this list.
    -->
    <xs:complexType name="Frequency">
        <xs:simpleContent>
            <xs:extension base="xs:token">
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="vocabulary">
        <xs:complexType>
            <xs:all>
                <xs:element name="kanji">
                    <xs:complexType>
                        <xs:choice minOccurs="0" maxOccurs="unbounded">
                            <xs:element name="set" type="Set" />
                            <xs:element name="visually_similar" type="VisuallySimilar" />

                            <!-- freq should only occur once, but we can't express this in xs apparently -->
                            <xs:element name="freq" type="Frequency" />
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== digorydoo/goigoi/goigoi-xml/voc_ja/900_kanji_index.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schema/kanji_index_schema.xsd"
>
    <kanji>
        <!--
            These are manual kanji-index corrections. They will override the levels extracted by extractKanjiList,
            which is based on the levels of the words they appear in.
        -->

        <!-- N5 according to jlptstudy.net -->
        <set lvl="n5">一七万三上下中九二五人今休会何先入八六円出分前北十千午半南友口古右名四国土外多大</set>
        <set lvl="n5">天女子学安小少山川左年店後手新日時書月木本来東校母毎気水火父生男白百目社空立耳聞</set>
        <set lvl="n5">花行西見言話語読買足車週道金長間雨電食飲駅高魚</set>

        <!-- N4 according to jlptstudy.net (altough I moved some) -->
        <set lvl="n4">不世主代以低住借光別力区医合味品員回地堂場売屋森業菜験室工市帰度建弱強思急悪意教</set>
        <set lvl="n4">文旅族映昼暑暗曜有服考者習首歌止正民注洋洗漢牛特産用画界病発県着短研秋究紙終館顔</set>
        <set lvl="n4">飯親計試説貸質走起軽送通進運都野銀開院集音頭題</set>

        <!-- I force these to N5 even though jlptstudy.net rates them N4 -->
        <set lvl="n5">乗事京仕体作使便働元兄写真冬切勉動去同図夏夜太好姉始字家寒広引所持料方早明春朝村</set>
        <set lvl="n5">林楽歩死池海理田知私肉自色英薬赤転近遠門青鳥物町</set>

        <!-- N3 according to jlptstudy.net (although I moved some) -->
        <set lvl="n3">丁争付令仲伝位例係倉倍候停健側億兆児全共兵具典冷刀列利刷副功加類飛貨貯費</set>
        <set lvl="n3">助努労勇勝包協博印原参反受史司各向告命和商喜器囲固園坂型士夫衣録関郡里量</set>
        <set lvl="n3">央失委季孫完官定実客宮害察局岩岸州巣差希帯帳平底府庫庭康式弓形役未遊達選</set>
        <set lvl="n3">径徒得必念想愛感成戦才打投折拾挙改放救敗散数整旗昔星昭景晴曲望期陸追速連</set>
        <set lvl="n3">札材束松板柱栄根梅械植極標橋機欠歴殺毒氏求汽法波泣泳流路麦辞農返養談議訓</set>
        <set lvl="n3">浅浴消深清温湖湯満漁灯炭然焼照熱牧玉王球由申畑登皮省矢礼祝票賞陽身軍輪詩</set>
        <set lvl="n3">祭福科秒種積章童競笛第等算管箱節粉紀約級細組給絵線置羊羽老育鼻馬隊静順課</set>
        <set lvl="n3">胃脈腸臣航船良芸芽苦落葉街要観</set>

        <!-- I forced these to N4 even though jlptstudy.net rates them N3 -->
        <set lvl="n4">歯毛点鳴米糸美草虫血覚角辺部酒雪雲面願谷豆象貝負竹氷油丸予公</set>

        <!-- Rated N4, because they appear in GENKI1 kanji section -->
        <set lvl="n4" rem="GENKI1 p.346">々</set>

        <!-- Rated N4, because they appear in GENKI2 kanji section -->
        <set lvl="n4" rem="GENKI2 p.274">特港</set>
        <set lvl="n4" rem="GENKI2 p.281">彼代留族親急医者</set>
        <set lvl="n4" rem="GENKI2 p.287">意味注寺借走場建地鉄通</set>
        <set lvl="n4" rem="GENKI2 p.293">世界考開運教室以</set>
        <set lvl="n4" rem="GENKI2 p.299">野習歳集発表品活結婚</set>
        <set lvl="n4" rem="GENKI2 p.306">的洋服堂力授業試験貸館終宿題</set>
        <set lvl="n4" rem="GENKI2 p.313">様不漢卒工研究質</set>
        <set lvl="n4" rem="GENKI2 p.321">止枚両無払笑絶対痛最続</set>
        <set lvl="n4" rem="GENKI2 p.328">信経若送幸計遅配</set>
        <set lvl="n4" rem="GENKI2 p.334">記銀回用末残説案内守</set>
        <set lvl="n4" rem="GENKI2 p.340">顔悲怒違比調化横相</set>

        <!-- Rated N5, even though they appear in GENKI2 kanji section -->
        <set lvl="n5" rem="GENKI2 p.313">問</set>
        <set lvl="n5" rem="GENKI2 p.321">皿声茶心</set>
        <set lvl="n5" rem="GENKI2 p.328">風犬台初弟妹重</set>
        <set lvl="n5" rem="GENKI2 p.334">黒待番夕忘</set>
        <set lvl="n5" rem="GENKI2 p.340">変果答</set>

        <!-- Rated N4 according to jisho kanji details -->
        <set lvl="n4">有室教題族洋習漢野</set>

        <!-- Rated N3 according to jisho kanji details -->
        <set lvl="n3">
            静構欲吸頼渡遊成居側雑箱局辞段差腹散除窓官警関徒達機飛険財交皆幾緒祖込常非杯偶確適単恥怖迎訪増亡倒眠暮決戻探捕盗逃過似越途因支術
            際規政慣割舞神存夢席寄妻値済髪宅務退報指娘息性師観参加頂御処刻突互到煙更抜与恐抱偉
        </set>

        <!-- Rated N2 according to jisho kanji details -->
        <set lvl="n2">
            薄黄緑磨被筆誌郵筒封菓塩階喫蔵濯掃瓶紅符奥勢練砂悩績専券税布荷帽零涼戸詰個久複簡珍硬片換伺混移触届祈召塗捨捜沸泊介紹拝震技貿則周
            復講絡律隅裏畳団贈郊踊棒泥柔将綿袋島枝腕床駐普減編乾再耕肯虎般療湾肌傾含雇双塔齢依占軒賢濃鋭巨涙香肩患腰汗幅爆了跡缶況販叫伸沈凍
            刺替曇
        </set>

        <!-- Rated N1 according to jisho kanji details -->
        <set lvl="n1">
            隣締撮跳履鉛廊玄暇緊攻豚巡麗綺煩伯懸暫駄寧寂酷堅揺騒驚褒飾漬頑致仰踏滑壊呉渇慮剤携房為臭趣壁翻漫釣嬢輩如陰免抵蚊殴詐欺塾也叶又宜
            智悠津奴凶酷艶哉是唯徐端既頻瞬即穫択析沖施逮克衝抗眺範儀掲較貢献審及罰奇陥雰監督裸睡嫁悟援歓憩鎖憶泡嬉癖徴痴翼需炎縄裕堪堀誇粗秀
            穏誘猿丘雷漠稲霧奨魔寮嵐離冗霜刑徹斎柄薦慢僚維鬼惑芝拍卓塀契融哲渋滞勘恵企環症請釈診冒滅魅響隠腐微繰黙輝振撃怠握劣奪稼訴譲狂避勧
            刈飽覆酔扱詳緩鮮妙哀屈慎沢厄豪華剣愉縁
        </set>

        <!-- Rated Nx according to jisho kanji details -->
        <set lvl="-">
            〜贅莫稍埃紐諺或鞄斯頃貰苛筈兎喉萄葡髭騙臍悉咄咎嗟殆叩
        </set>

        <!--
            I disagree with jisho kanji details.
            * For instance, jisho has nx for 蹴, but 蹴る is an n2 word and not marked as usually in kana; but if it's
              a kanji that hardly anybody knows, the word should be usually in kana. I moved those kanjis to N2.
            * 吹く・ふく and 服・ふく are both N5 words, and neither is usually in kana, but if we leave 吹 at N3, this
              would create ambiguity for N5 learners. I moved at least one of those kanjis to the word JLPT level
              instead, or sometimes moved the word to another JLPT level.
            * Also: Jisho does not agree with GENKI:
              jisho rates 結 as N1 even though it appears in GENKI2 kanji section
              jisho rates 無 as Nx even though it appears in GENKI2 kanji section
        -->
        <set lvl="n5">靴晩背号乳卵傘取閉勤困可丈次昨当石呂机箸猫供易吹</set>
        <set lvl="n4">椅飴他誰忙甘汚危狭難嫌押呼並聴脱弾咲座寝貼疲降灰匹冊君僕直治優</set>
        <set lvl="n3">匂咳坊張厚尋泉俺棚邪辛吐影恋</set>
        <set lvl="n2">痩鍵鍋戚膝尻粧挨拶袖謎諦溺羨僅餌脇畏描鹸喧嘩濡嘘頬噂掴剃叱吠唸噛</set>
        <set lvl="n1">遣噌碗醤馳賑</set>

        <!--
            These kanjis are taught in school, therefore it doesn't make sense to make them harder than N2.
        -->
        <set lvl="n2">
            幹皇液圧策往干縮蒸朗暴河詞序群系脳総巻採仮刊熟孝庁臨奮潮聖班沿樹閣創肥唱衆賀諸鋼俵宣忠揮己肺磁鏡縦糖誕保眼弁派暖盛敵素舎厳謝飼覧
            展興障義訳射絹故護看扇蹴尺
        </set>

        <!-- By school year https://en.wikipedia.org/wiki/Ky%C5%8Diku_kanji -->
        <set schoolyear="1">
            一二三四五六七八九十百千上下左右中大小月日年早木林山川土空田天生花草虫犬人名女男
            子目耳口手足見音力気円入出立休先夕本文字学校村町森正水火玉王石竹糸貝車金雨赤青白
        </set>
        <set schoolyear="2">
            数多少万半形太細広長点丸交光角計直線矢弱強高同親母父姉兄弟妹自友体毛頭顔首心時曜
            朝昼夜分週春夏秋冬今新古間方北南東西遠近前後内外場地国園谷野原里市京風雪雲池海岩
            星室戸家寺通門道話言答声聞語読書記紙画絵図工教晴思考知才理算作元食肉馬牛魚鳥羽鳴
            麦米茶色黄黒来行帰歩走止活店買売午汽弓回会組船明社切電毎合当台楽公引科歌刀番用何
        </set>
        <set schoolyear="3">
            丁世両主乗予事仕他代住使係倍全具写列助勉動勝化区医去反取受号向君味命和品員商問坂
            央始委守安定実客宮宿寒対局屋岸島州帳平幸度庫庭式役待急息悪悲想意感所打投拾持指放
            整旅族昔昭暑暗曲有服期板柱根植業様横橋次歯死氷決油波注泳洋流消深温港湖湯漢炭物球
            由申界畑病発登皮皿相県真着短研礼神祭福秒究章童笛第筆等箱級終緑練羊美習者育苦荷落
            葉薬血表詩調談豆負起路身転軽農返追送速進遊運部都配酒重鉄銀開院陽階集面題飲館駅鼻
        </set>
        <set schoolyear="4">
            不争付令以仲伝位低例便信倉候借停健側働億兆児共兵典冷初別利刷副功加努労勇包卒協単
            博印参史司各告周唱喜器囲固型堂塩士変夫失好季孫完官害察巣差希席帯底府康建径徒得必
            念愛成戦折挙改救敗散料旗昨景最望未末札材束松果栄案梅械極標機欠歴残殺毒氏民求治法
            泣浅浴清満漁灯無然焼照熱牧特産的省祝票種積競笑管節粉紀約結給続置老胃脈腸臣航良芸
            芽英菜街衣要覚観訓試説課議象貨貯費賞軍輪辞辺連達選郡量録鏡関陸隊静順願類飛飯養験
        </set>
        <set schoolyear="5">
            久仏仮件任似余価保修俵個備像再刊判制券則効務勢厚句可営因団圧在均基報境墓増夢妻婦
            容寄富導居属布師常幹序弁張往復徳志応快性恩情態慣承技招授採接提損支政故敵断旧易暴
            条枝査格桜検構武比永河液混減測準演潔災燃版犯状独率現留略益眼破確示祖禁移程税築精
            素経統絶綿総編績織罪群義耕職肥能興舌舎術衛製複規解設許証評講謝識護豊財貧責貸貿賀
            資賛質輸述迷退逆造過適酸鉱銅銭防限険際雑非預領額飼
        </set>
        <set schoolyear="6">
            並乱乳亡仁供俳値傷優党冊処刻割創劇勤危卵厳収后否吸呼善困垂城域奏奮姿存孝宅宇宗宙
            宝宣密寸専射将尊就尺届展層己巻幕干幼庁座延律従忘忠憲我批担拝拡捨探推揮操敬映晩暖
            暮朗机枚染株棒模権樹欲段沿泉洗派済源潮激灰熟片班異疑痛皇盛盟看砂磁私秘穀穴窓筋策
            簡糖系紅納純絹縦縮署翌聖肺背胸脳腹臓臨至若著蒸蔵蚕衆裁装裏補視覧討訪訳詞誌認誕誠
            誤論諸警貴賃遺郵郷針鋼閉閣降陛除障難革頂骨
        </set>
        <!--
            Jisho says "taught in junior high" for these, so schoolyear could be 7, 8, 9.
        -->
        <set schoolyear="7">
            扇俺蹴箸猫曇靴傘棚呂邪辛丈怒払彼僕匹々歳婚遅違椅飴誰忙甘汚狭嫌押聴脱弾咲寝貼疲匂
            咳偶尋痩鍵鍋戚膝尻粧挨拶袖謎諦溺羨僅餌脇畏到煙更抜与恐抱偉突互御頼渡皆幾緒込杯恥
            怖迎倒眠戻捕盗逃越途舞髪娘吹坊描替影恋吐
        </set>

        <!--
            Visually similar kanjis.

            Do not include non-Japanese characters, because doing so could lead to missing glyph problems with Android
            system fonts. Also, learners should be presented characters that they're going to learn at some point;
            presenting additional characters only leads to confusion.

            Note that kanjis that are not used by any word in our vocabulary cannot be used here, because they are
            removed from the list of kanjis by frequency before the check against non-standard kanjis is performed.

            Note that it's OK to have just two kanjis in a group, because Goigoi multiplies the possibilities for words
            that are made of multiple kanjis.
        -->
        <visually_similar>
            <group>人入八</group><!-- too similar in some fonts: ハ -->
            <group>犬太父交</group>
            <group>大六穴立</group>
            <group>木本体休</group>
            <group>夫矢失央</group><!-- 夫 and 末 are too similar -->
            <group>小少歩赤ホ</group>
            <group>当ヨ三狂</group>
            <group>川山出片</group>
            <group>十土末</group><!-- 土 and 士 are too similar -->
            <group>上士止吐</group>
            <group>来米光半</group>
            <group>先洗缶</group>
            <group>文才丈又</group>
            <group>仕壮針汁</group>
            <group>行作任件</group>
            <group>天元示完</group>
            <group>年牛午生</group>
            <group>千チ干平</group>
            <group>手毛未テ</group>
            <group>王正玉主</group>
            <group>方万坊肪</group>
            <group>五互瓦与</group>
            <group>写汚号呉</group>
            <group>工功虹紅</group>
            <group>不下丁</group>
            <group>刀力九丸</group>
            <group>刃切初幼</group>
            <group>クマ々</group>
            <group>日白目自</group>
            <group>月耳母身</group>
            <group>兄豆克冗</group>
            <group>祝況児視</group>
            <group>競鋭脱説</group>
            <group>血皿且旧</group>
            <group>甘音昔普</group>
            <group>其基甚碁</group>
            <group>見貝具臭</group>
            <group>買員貴貢</group>
            <group>肯督景帽</group>
            <group>覧貸貨賃</group>
            <group>貿質貧資</group>
            <group>積漬潰演</group>
            <group>算県省昇</group>
            <group>宿直値境</group>
            <group>営労栄賞</group>
            <group>覚党堂常</group>
            <group>学字宇宅</group>
            <group>了子予</group>
            <group>町釘頂</group>
            <group>竹付打灯</group>
            <group>村材対符</group>
            <group>早卓草章</group>
            <group>田申由曲</group>
