=== digorydoo/goigoi/goigoi-xml/schema/vocab_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        JLPT level associated with this item. The value "-" explicitly states the item is not associated with any
        particular JLPT level.
    -->
    <xs:simpleType name="JLPTLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="n5" />
            <xs:enumeration value="n4" />
            <xs:enumeration value="n3" />
            <xs:enumeration value="n2" />
            <xs:enumeration value="n1" />
            <xs:enumeration value="-" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Comma-separated list of JLPT levels.
    -->
    <xs:simpleType name="JLPTLevelList">
        <!--
            xs:list itemType="JLPTLevel" doesn't work, because we want a comma-separated list, which reads better
        -->
        <xs:restriction base="xs:string">
            <xs:pattern value="-|n[1-5](,\s*(-|n[1-5]))*" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Tells whether the word should be studied in context rather than on its own.
        Typically used for abstract words whose descriptions are rather hard to grasp.
    -->
    <xs:simpleType name="StudyInContext">
        <xs:restriction base="xs:string">
            <xs:enumeration value="preferred" />
            <xs:enumeration value="required" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        The topic divides the entire vocabulary into large sections. There should only be a few.
    -->
    <xs:complexType name="Topic">
        <xs:attribute name="name_ja" type="xs:string" use="required" />
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="notice_en" type="xs:string" use="required" />
        <xs:attribute name="imgSrc" type="xs:string" />
        <xs:attribute name="bgColour" type="xs:string" />
        <xs:attribute name="linkText" type="xs:string" />
        <xs:attribute name="linkHref" type="xs:string" />
    </xs:complexType>

    <!--
        The unyts of a topic can be grouped by putting a subheader before each group of unyts.
    -->
    <xs:complexType name="TopicSubheader">
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
    </xs:complexType>

    <!--
        A unyt is a lesson. It's called unyt and not unit to avoid confusion with Kotlin type Unit.
    -->
    <xs:complexType name="Unyt">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="section" type="UnytSection" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
        <xs:attribute name="hasRomaji" type="xs:boolean" use="required" />
        <xs:attribute name="hasFurigana" type="xs:boolean" use="required" />
        <xs:attribute name="defaultHint_en" type="xs:string" />
        <xs:attribute name="defaultHint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="requiresSentences" type="xs:boolean" />
        <xs:attribute name="requiresPhrases" type="xs:boolean" />
        <xs:attribute name="ignoresCombinedReadings" type="xs:boolean" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />
    </xs:complexType>

    <!--
        The words of a unyt can be grouped by wrapping them into sections.
        If there is only one section in a unyt, it can be anonymous, otherwise at least name_en is required.
    -->
    <xs:complexType name="UnytSection">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="word" type="Word" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
    </xs:complexType>

    <!--
        A word in the vocabulary inside a particular unyt.
    -->
    <xs:complexType name="Word">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="phrase" type="Phrase" />
            <xs:element name="sentence" type="Sentence" />
            <xs:element name="keep_apart_from" type="KeepApartFrom" />
            <xs:element name="keep_together" type="KeepTogether" />
            <xs:element name="see" type="SeeAlso" />
            <xs:element name="accept_for_translation" type="WordAcceptForTranslation" />
        </xs:choice>

        <!--
            The word is defined with the `w` attribute. If the word has kana, we need to provide furigana. The furigana
            also defines the kana reading. The place where the okurigana is put matters: If it is put outside the
            furigana, it becomes actual okurigana, but if it is put inside the furigana, it becomes mere pronounciation.
            For instance, "【取：と】り【上：あ】げる" and "【取：とり】【上：あ】げる" both define the kana as "とりあげる", but
            the kanji rendering of the former is "取り上げる" (with okurigana), while the kanji rendering of the latter
            is "取上げる" (without okurigana). We usually use the most common rendering as the `w` parameter and mark
            other acceptable forms with <accept_for_translation>.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="Langenscheidt" type="xs:string" />
        <xs:attribute name="hint_en" type="xs:string" />
        <xs:attribute name="hint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="dict" type="xs:string" />
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="usuallyInKana" type="xs:boolean" />
        <xs:attribute name="hasCombinedReading" type="xs:boolean" />
        <xs:attribute name="common" type="xs:boolean" />
        <xs:attribute name="studyInContext" type="StudyInContext" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />

        <!--
            The category is restricted, see enum class WordCategory.
            We don't use xs:enumeration/xs:list here, because unfortunately, members of xs:list are separated by
            whitespace only, which reads very confusingly, e.g. "old-fashioned plant" instead of "old-fashioned, plant".
        -->
        <xs:attribute name="category" type="xs:string" />
    </xs:complexType>

    <!--
        Phrases are short, usually not full sentences, and never end with a punctuation character.
    -->
    <xs:complexType name="Phrase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="ph" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Sentences are longer than phrases, should be full sentences, and must end with a punctuation character.
    -->
    <xs:complexType name="Sentence">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="s" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        When the word is used inside a phrase or sentence in a different form rather than its dictionary form, we need
        to declare how the App should ask about the word.
    -->
    <xs:complexType name="Ask">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="accept" type="AskAccept" />
        </xs:choice>

        <!-- Either "w" alone or both "stem" and "suffix" are required, but we cannot express this in XSD 1.0 -->
        <xs:attribute name="w" type="xs:string" />
        <xs:attribute name="stem" type="xs:string" />
        <xs:attribute name="suffix" type="xs:string" />
    </xs:complexType>

    <!--
        Marks a word as potentially confusing together with another word. These words should not be studied together,
        and they must appear in different unyts. We usually mark synonyms and almost synonyms with this, and sometimes
        words whose declared phrases become ambiguous when the user may enter either of them.
    -->
    <xs:complexType name="KeepApartFrom">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Marks words that should be studied together. If their JLPT levels match, they should also be kept in the same
        unyt. We use this mostly for hidden words that should not wander from another, non-hidden word that is
        essentially the same, such as 風呂 and お風呂.
    -->
    <xs:complexType name="KeepTogether">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Adds a see-also link from this word to another.
    -->
    <xs:complexType name="SeeAlso">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="type" type="SeeAlsoType" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        The type of see-also link
    -->
    <xs:simpleType name="SeeAlsoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="adjective" />
            <xs:enumeration value="antonym" />
            <xs:enumeration value="closely related" />
            <xs:enumeration value="noun" />
            <xs:enumeration value="v.i." />
            <xs:enumeration value="v.t." />
            <xs:enumeration value="verb" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        When the user is presented the translation of a word without the context of a phrase or sentence, we can add
        more acceptable answers.
    -->
    <xs:complexType name="WordAcceptForTranslation">
        <!--
            The attribute `w` takes furigana; both kanji/okurigana and kana parts become acceptable answers. For
            instance, if w="【入：い】り【口：ぐち】", we'd accept either 入り口 or いりぐち.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <!--
            Marks this variant as inaccurate. The app will not count this answer as wrong, but will encourage the user
            to use the expected answer instead.
        -->
        <xs:attribute name="inaccurate" type="xs:boolean" />

        <!--
            Marks this variant as always interchangable. If you set this to "true", the variant will also be allowed in
            phrases and sentences when they use the word in the exact form as it was defined. If the phrase or sentence
            uses the word in a slightly altered form (e.g. not in dictionary form if it's a verb), the variant is still
            not allowed, because the app cannot apply the form directly. In those cases, mark the acceptable answers
            with <accept> inside <ask>. On the other hand, if you set interchangable="false", the variant will never
            be allowed in phrases and sentences.

            If the word's kana reading and the variant's kana reading are the same, the variant is treated as an
            alternate spelling. In that case, specifying `interchangeable` is required. If the word's kanji/okurigana
            and the variant's kanji/okurigana are the same, the variant is treated as an alternate reading. In that
            case, too, specifying `interchangeable` is required. Otherwise, `interchangeable` is optional and defaults
            to "false".

            Examples: (i) Suppose the word is defined as w="【入：いり】【口：ぐち】", and an acceptable answer is defined
            as w="【入：い】り【口：ぐち】". The kana reading is いりぐち for both variants, so the app will treat this as an
            alternate spelling. Set interchangeable="true" to allow using this variant in phrases and sentences.

            (ii) Word defined as w="【早：はや】い", translation is "early; fast", acceptable for this translation is
            w="【速：はや】い", whose translation is "fast". The kana reading is はやい for both variants, and the app will
            treat this as an alternate spelling. However, the alternate spelling cannot be used in a phrase or sentence
            whose context makes it clear that the meaning is "early", not "fast". Set interchangeable="false".

            (iii) Word defined as w="【描：えが】く", translation is "to draw; to paint", acceptable answer is
            w="【描：か】く". The kanji/okurigana is 描く for both variants, so the app will treat this as an alternate
            reading. If the app asks the user to type their answer in kana given the translation "to draw; to paint",
            we'll accept かく. Using that reading in a phrase or sentence about "【描：えが】く" might be acceptable, but
            in some cases it might lead to confusion with "【書：か】く". Better set interchangeable="false".
        -->
        <xs:attribute name="interchangeable" type="xs:boolean" />

        <!--
            Remark, ignored by the app.
        -->
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="AskAccept">
        <xs:attribute name="w" type="xs:string" use="required" />
        <xs:attribute name="suffix" type="xs:string" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        This is the root of the XML document.
    -->
    <xs:element name="vocabulary">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="topic" type="Topic" />
                <xs:element name="subheader" type="TopicSubheader" />
                <xs:element name="unit" type="Unyt" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== digorydoo/goigoi/goigoi-xml/voc_ja/010_n4/300_n4_hidden_unsorted.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="Hidden N4 words"
      hasRomaji="true"
      hasFurigana="true"
      lvl="n4"
      HIDDEN="true"
      ignoresCombinedReadings="false"
    >
        <section>
            <!--
                To check whether there are more N4 words still missing, use:
                $ node src/jishoToGoigoi.js __jlpt=n4 __goigoi=filter
            -->

            <!-- verbs -->
            <word
              w="【込：こ】む"
              rom="komu"
              tr_en="to be crowded; to be packed; to be congested"
              hint_en="v.i."
              lvl="n4"
              rem="komu-crowded is included in N4 with different kanji 混む"
              id="komu-crowded-alt"
            />

            <!-- pronouns and particles -->
            <word
              w="【僕：ぼく】"
              rom="boku"
              tr_en="I; me"
              hint_en="male term"
              hint_de="männliche Sprache"
              lvl="n4"
            />
            <word
              w="【君：きみ】"
              rom="kimi"
              tr_en="you; buddy; pal"
              lvl="n4"
              id="kimi-you"
              rem="rarely used except in movies and song lyrics; ChatGPT disagrees, though"
            />

            <!-- unsorted -->
            <word
              w="どうぞ【宜：よろ】しく"
              rom="dōzo yoroshiku"
              tr_en="pleased to meet you; how do you do"
              hint_en="expression"
              hint_de="Ausdruck"
              lvl="n4"
              HIDDEN="true"
              rem="jisho has n2"
            />
            <word
              w="あっ"
              rom="a"
              tr_en="Ah! Oh! Hey!"
              lvl="n4"
            />
            <word
              w="うん"
              rom="un"
              tr_en="yes; yeah; uh huh / hum; hmmm; well; erm / oof"
              lvl="n4"
              id="un-yeah"
            />
            <word
              w="そう"
              rom="sō"
              tr_en="appearing that; looking like"
              hint_en="auxiliary"
              lvl="n4"
              id="sō-appearing"
            />
            <word
              w="【火：ひ】"
              rom="hi"
              tr_en="fire; flame"
              hint_en="noun; suffix"
              lvl="n4"
              category="fire"
              id="hi-fire"
            />
            <word
              w="【子：こ】"
              rom="ko"
              tr_en="child; young"
              hint_en="noun; suffix"
              lvl="n4"
            />
            <word
              w="【市：し】"
              rom="shi"
              tr_en="city"
              hint_en="noun; suffix"
              lvl="n4"
              id="shi-city-notilde"
              rem="n4_nouns_6 has 〜 in w"
            />
            <word
              w="【斯：こ】う"
              rom="kou"
              tr_en="in this way; thus"
              hint_en="adverb"
              lvl="n4"
              id="kou-thus"
            />
            <word
              w="あんな"
              rom="anna"
              tr_en="that sort of; that kind of; like that; such; so"
              hint_en="pre-noun adjectival (rentaishi)"
              lvl="n4"
            />
            <word
              w="そんな"
              rom="sonna"
              tr_en="such; that sort of; that kind of; like that / no way!; never!"
              hint_en="pre-noun adjectival (rentaishi)"
              lvl="n4"
            />
            <word
              w="ああ"
              rom="aa"
              tr_en="like that; so"
              lvl="n4"
              id="aa-so"
              HIDDEN="true"
              rem="not a good word"
            />
        </section>
    </unit>
</vocabulary>

=== digorydoo/goigoi/goigoi-xml/voc_ja/000_n5/140_n5_hidden_unsorted.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="Hidden N5 words"
      hasRomaji="true"
      hasFurigana="true"
      lvl="n5"
      HIDDEN="true"
      ignoresCombinedReadings="false"
    >
        <section>
            <word
              w="【山：やま】【田：だ】"
              rom="Yamada"
              tr_en="Mr Yamada"
              lvl="n5"
              HIDDEN="true"
              rem="just to provide the reading for the furigana check of sentences"
            />
            <word
              w="【小：こ】【林：ばやし】"
              rom="Kobayashi"
              tr_en="Mr Kobayashi"
              lvl="n5"
              HIDDEN="true"
              rem="just to provide the reading for the furigana check of sentences"
            />
            <word
              w="【高：たか】【木：ぎ】"
              rom="Takagi"
              tr_en="Mr Takagi"
              lvl="n5"
              HIDDEN="true"
              rem="just to provide the reading for the furigana check of sentences"
            />

            <!-- expression -->
            <word
              w="【木：こ】の 【葉：は】"
              rom="ko no ha"
              tr_en="leaves of a tree"
              lvl="n5"
              HIDDEN="true"
              rem="just to provide the reading; jisho has nx for このは"
              href="https://hinative.com/questions/22085422"
            />

            <!-- pronouns and particles -->
            <word
              w="こんな"
              rom="konna"
              tr_en="this sort of; such"
              lvl="n5"
            />
            <word
              w="こんなに"
              rom="konna ni"
              tr_en="so; like this; in this way"
              hint_en="adverb"
              lvl="n5"
              rem="jisho has n3"
            />
            <word
              w="こちら"
              rom="kochira"
              tr_en="this way; this direction"
              lvl="n5"
            />
            <word
              w="あそこ"
              rom="asoko"
              tr_en="there; over there"
              lvl="n5"
            />
            <word
              w="あちら"
              rom="achira"
              tr_en="that way; over there; yonder"
              hint_en="far from both speaker and listener"
              hint_de="weit weg"
              lvl="n5"
              rem="appears in GENKI2 L20 vocab section with the remark 'polite'; is this really n5?"
            />
            <word
              w="はい"
              rom="hai"
              tr_en="yes"
              lvl="n5"
            />
            <word
              w="ええ"
              rom="ee"
              tr_en="yes; that is correct; huh?"
              lvl="n5"
            />
            <word
              w="いいえ"
              rom="iie"
              tr_en="no"
              lvl="n5"
            />

            <!-- adjective -->
            <word
              w="【大：おお】きな"
              rom="ōki na"
              tr_en="big; large; great"
              hint_en="adj."
              lvl="n5"
            />
            <word
              w="【小：ちい】さな"
              rom="chīsa na"
              tr_en="small; little; tiny"
              hint_en="adj."
              lvl="n5"
            />

            <!-- adverb -->
            <word
              w="どうも"
              rom="dōmo"
              tr_en="thanks; very (sorry); hello; goodbye"
              hint_en="adverb"
              lvl="n5"
            />
            <word
              w="【一：いっ】【緒：しょ】"
              rom="issho"
              tr_en="together; at the same time"
              hint_en="adverb; noun"
              lvl="n5"
            />

            <!-- verb -->
            <word
              w="【来：こ】ない"
              rom="konai"
              tr_en="I don't come"
              lvl="n5"
              HIDDEN="true"
              rem="just to provide the reading for the furigana check of sentences"
            />

            <!-- prefix, suffix -->
            <word
              w="【来：らい】"
              rom="rai"
              tr_en="next (year, spring, etc.); coming"
              hint_en="prefix; suffix"
              lvl="n5"
              id="rai-next"
              HIDDEN="true"
              rem="not a good word; jisho has n3"
            />

            <!-- unsorted -->
            <word
              w="【有：あ】り【難：がと】う"
              rom="arigatou"
              tr_en="thank you; thanks"
              usuallyInKana="true"
              lvl="n5"
              id="arigatou-thanks"
              rem="jisho has n3"
            >
                <keep_apart_from id="okage-grace" />
                <keep_apart_from id="kansha-thanks" />
                <keep_apart_from id="arigatou-thxalt" />
                <keep_together id="arigatou-thxalt" />
            </word>
            <word
              w="【有：あり】【難：がと】う"
              rom="arigatou"
              tr_en="thank you; thanks"
              usuallyInKana="true"
              lvl="n5"
              id="arigatou-thxalt"
              rem="jisho has n3"
            >
                <keep_apart_from id="arigatou-thanks" />
                <keep_together id="arigatou-thanks" />
            </word>
            <word
              w="【頂：いただ】きます"
              rom="itadakimasu"
              tr_en="thank you (for the meal just served); I receive (this meal)"
              hint_en="expressions (phrases, clauses, etc.)"
              lvl="n5"
              usuallyInKana="true"
              rem="jisho has n3"
            />
            <word
              w="もう【一：いち】【度：ど】"
              rom="mō ichi-do"
              tr_en="once more; again"
              hint_en="expressions (phrases, clauses, etc.)"
              lvl="n5"
              HIDDEN="true"
              rem="is a phrase in counters_3"
            />
            <word
              w="【御：ご】【免：めん】なさい"
              rom="gomen nasai"
              tr_en="I'm sorry; my apologies; excuse me; pardon me"
              hint_en="expressions (phrases, clauses, etc.)"
              lvl="n5"
              rem="jisho has n3"
              usuallyInKana="true"
            />
            <word
              w="【如何：どう】して"
              rom="dō shite"
              tr_en="how; in what way; by what means; why"
              hint_en="adverb (fukushi)"
              hasCombinedReading="true"
              lvl="n5"
            />
            <word
              w="あの"
              rom="ano"
              tr_en="say; well; um; er"
              lvl="n5"
            />
            <word
              w="その"
              rom="sono"
              tr_en="that; the"
              lvl="n5"
              id="sono-that"
            />
            <word
              w="この"
              rom="kono"
              tr_en="this"
              lvl="n5"
              id="kono-this"
              HIDDEN="true"
              rem="must not be together with kore"
            />
            <word
              w="さあ"
              rom="sā"
              tr_en="come; come now; well; let's see"
              hint_en="conjunction"
              lvl="n5"
            />
            <word
              w="じゃあ"
              rom="jā"
              tr_en="then; well; so"
              hint_en="conjunction"
              lvl="n5"
            />
            <word
              w="では"
              rom="de wa"
              tr_en="then; well then; if not ..."
              hint_en="conjunction"
              lvl="n5"
            />
            <word
              w="より"
              rom="yori"
              tr_en="than; out of; except"
              hint_en="particle"
              lvl="n5"
            />
            <word
              w="そうして"
              rom="sō shite"
              tr_en="and; like that"
              hint_en="conjunction"
              lvl="n5"
            />
            <word
              w="そして"
              rom="soshite"
              tr_en="and then; thus"
              hint_en="conjunction"
              lvl="n5"
            />
            <word
              w="【一：ひと】【月：つき】"
              rom="hito-tsuki"
              tr_en="one month"
              hint_en="noun"
              lvl="n5"
            />
            <word
              w="どうぞ"
              rom="dōzo"
              tr_en="please; kindly; by all means"
              hint_en="adverb"
              lvl="n5"
            />
            <word
              w="【日：にち】"
              rom="nichi"
              tr_en="day (of the month); Sunday; counter for days"
              tr_de="Tag (des Monats); Sonntag; Zähler für Tage"
              lvl="n5"
              id="nichi-day"
              HIDDEN="true"
              rem="kind of wrong, because 日 by itself is usually pronounced hi; jisho has n3"
            />
            <word
              w="【今：こん】【日：にち】は"
              rom="konnichi wa"
              tr_en="hello; good day; good afternoon"
              lvl="n5"
              usuallyInKana="true"
              HIDDEN="true"
              rem="this is a phrase; jisho has n3"
            />
        </section>
    </unit>
</vocabulary>
