=== digorydoo/goigoi/goigoi-xml/schema/vocab_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        JLPT level associated with this item. The value "-" explicitly states the item is not associated with any
        particular JLPT level.
    -->
    <xs:simpleType name="JLPTLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="n5" />
            <xs:enumeration value="n4" />
            <xs:enumeration value="n3" />
            <xs:enumeration value="n2" />
            <xs:enumeration value="n1" />
            <xs:enumeration value="-" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Comma-separated list of JLPT levels.
    -->
    <xs:simpleType name="JLPTLevelList">
        <!--
            xs:list itemType="JLPTLevel" doesn't work, because we want a comma-separated list, which reads better
        -->
        <xs:restriction base="xs:string">
            <xs:pattern value="-|n[1-5](,\s*(-|n[1-5]))*" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Tells whether the word should be studied in context rather than on its own.
        Typically used for abstract words whose descriptions are rather hard to grasp.
    -->
    <xs:simpleType name="StudyInContext">
        <xs:restriction base="xs:string">
            <xs:enumeration value="preferred" />
            <xs:enumeration value="required" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        The topic divides the entire vocabulary into large sections. There should only be a few.
    -->
    <xs:complexType name="Topic">
        <xs:attribute name="name_ja" type="xs:string" use="required" />
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="notice_en" type="xs:string" use="required" />
        <xs:attribute name="imgSrc" type="xs:string" />
        <xs:attribute name="bgColour" type="xs:string" />
        <xs:attribute name="linkText" type="xs:string" />
        <xs:attribute name="linkHref" type="xs:string" />
    </xs:complexType>

    <!--
        The unyts of a topic can be grouped by putting a subheader before each group of unyts.
    -->
    <xs:complexType name="TopicSubheader">
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
    </xs:complexType>

    <!--
        A unyt is a lesson. It's called unyt and not unit to avoid confusion with Kotlin type Unit.
    -->
    <xs:complexType name="Unyt">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="section" type="UnytSection" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
        <xs:attribute name="hasRomaji" type="xs:boolean" use="required" />
        <xs:attribute name="hasFurigana" type="xs:boolean" use="required" />
        <xs:attribute name="defaultHint_en" type="xs:string" />
        <xs:attribute name="defaultHint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="requiresSentences" type="xs:boolean" />
        <xs:attribute name="requiresPhrases" type="xs:boolean" />
        <xs:attribute name="ignoresCombinedReadings" type="xs:boolean" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />
    </xs:complexType>

    <!--
        The words of a unyt can be grouped by wrapping them into sections.
        If there is only one section in a unyt, it can be anonymous, otherwise at least name_en is required.
    -->
    <xs:complexType name="UnytSection">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="word" type="Word" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
    </xs:complexType>

    <!--
        A word in the vocabulary inside a particular unyt.
    -->
    <xs:complexType name="Word">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="phrase" type="Phrase" />
            <xs:element name="sentence" type="Sentence" />
            <xs:element name="keep_apart_from" type="KeepApartFrom" />
            <xs:element name="keep_together" type="KeepTogether" />
            <xs:element name="see" type="SeeAlso" />
            <xs:element name="accept_for_translation" type="WordAcceptForTranslation" />
        </xs:choice>

        <!--
            The word is defined with the `w` attribute. If the word has kana, we need to provide furigana. The furigana
            also defines the kana reading. The place where the okurigana is put matters: If it is put outside the
            furigana, it becomes actual okurigana, but if it is put inside the furigana, it becomes mere pronounciation.
            For instance, "【取：と】り【上：あ】げる" and "【取：とり】【上：あ】げる" both define the kana as "とりあげる", but
            the kanji rendering of the former is "取り上げる" (with okurigana), while the kanji rendering of the latter
            is "取上げる" (without okurigana). We usually use the most common rendering as the `w` parameter and mark
            other acceptable forms with <accept_for_translation>.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="Langenscheidt" type="xs:string" />
        <xs:attribute name="hint_en" type="xs:string" />
        <xs:attribute name="hint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="dict" type="xs:string" />
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="usuallyInKana" type="xs:boolean" />
        <xs:attribute name="hasCombinedReading" type="xs:boolean" />
        <xs:attribute name="common" type="xs:boolean" />
        <xs:attribute name="studyInContext" type="StudyInContext" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />

        <!--
            The category is restricted, see enum class WordCategory.
            We don't use xs:enumeration/xs:list here, because unfortunately, members of xs:list are separated by
            whitespace only, which reads very confusingly, e.g. "old-fashioned plant" instead of "old-fashioned, plant".
        -->
        <xs:attribute name="category" type="xs:string" />
    </xs:complexType>

    <!--
        Phrases are short, usually not full sentences, and never end with a punctuation character.
    -->
    <xs:complexType name="Phrase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="ph" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Sentences are longer than phrases, should be full sentences, and must end with a punctuation character.
    -->
    <xs:complexType name="Sentence">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="s" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        When the word is used inside a phrase or sentence in a different form rather than its dictionary form, we need
        to declare how the App should ask about the word.
    -->
    <xs:complexType name="Ask">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="accept" type="AskAccept" />
        </xs:choice>

        <!-- Either "w" alone or both "stem" and "suffix" are required, but we cannot express this in XSD 1.0 -->
        <xs:attribute name="w" type="xs:string" />
        <xs:attribute name="stem" type="xs:string" />
        <xs:attribute name="suffix" type="xs:string" />
    </xs:complexType>

    <!--
        Marks a word as potentially confusing together with another word. These words should not be studied together,
        and they must appear in different unyts. We usually mark synonyms and almost synonyms with this, and sometimes
        words whose declared phrases become ambiguous when the user may enter either of them.
    -->
    <xs:complexType name="KeepApartFrom">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Marks words that should be studied together. If their JLPT levels match, they should also be kept in the same
        unyt. We use this mostly for hidden words that should not wander from another, non-hidden word that is
        essentially the same, such as 風呂 and お風呂.
    -->
    <xs:complexType name="KeepTogether">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Adds a see-also link from this word to another.
    -->
    <xs:complexType name="SeeAlso">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="type" type="SeeAlsoType" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        The type of see-also link
    -->
    <xs:simpleType name="SeeAlsoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="adjective" />
            <xs:enumeration value="antonym" />
            <xs:enumeration value="closely related" />
            <xs:enumeration value="noun" />
            <xs:enumeration value="v.i." />
            <xs:enumeration value="v.t." />
            <xs:enumeration value="verb" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        When the user is presented the translation of a word without the context of a phrase or sentence, we can add
        more acceptable answers.
    -->
    <xs:complexType name="WordAcceptForTranslation">
        <!--
            The attribute `w` takes furigana; both kanji/okurigana and kana parts become acceptable answers. For
            instance, if w="【入：い】り【口：ぐち】", we'd accept either 入り口 or いりぐち.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <!--
            Marks this variant as inaccurate. The app will not count this answer as wrong, but will encourage the user
            to use the expected answer instead.
        -->
        <xs:attribute name="inaccurate" type="xs:boolean" />

        <!--
            Marks this variant as always interchangable. If you set this to "true", the variant will also be allowed in
            phrases and sentences when they use the word in the exact form as it was defined. If the phrase or sentence
            uses the word in a slightly altered form (e.g. not in dictionary form if it's a verb), the variant is still
            not allowed, because the app cannot apply the form directly. In those cases, mark the acceptable answers
            with <accept> inside <ask>. On the other hand, if you set interchangable="false", the variant will never
            be allowed in phrases and sentences.

            If the word's kana reading and the variant's kana reading are the same, the variant is treated as an
            alternate spelling. In that case, specifying `interchangeable` is required. If the word's kanji/okurigana
            and the variant's kanji/okurigana are the same, the variant is treated as an alternate reading. In that
            case, too, specifying `interchangeable` is required. Otherwise, `interchangeable` is optional and defaults
            to "false".

            Examples: (i) Suppose the word is defined as w="【入：いり】【口：ぐち】", and an acceptable answer is defined
            as w="【入：い】り【口：ぐち】". The kana reading is いりぐち for both variants, so the app will treat this as an
            alternate spelling. Set interchangeable="true" to allow using this variant in phrases and sentences.

            (ii) Word defined as w="【早：はや】い", translation is "early; fast", acceptable for this translation is
            w="【速：はや】い", whose translation is "fast". The kana reading is はやい for both variants, and the app will
            treat this as an alternate spelling. However, the alternate spelling cannot be used in a phrase or sentence
            whose context makes it clear that the meaning is "early", not "fast". Set interchangeable="false".

            (iii) Word defined as w="【描：えが】く", translation is "to draw; to paint", acceptable answer is
            w="【描：か】く". The kanji/okurigana is 描く for both variants, so the app will treat this as an alternate
            reading. If the app asks the user to type their answer in kana given the translation "to draw; to paint",
            we'll accept かく. Using that reading in a phrase or sentence about "【描：えが】く" might be acceptable, but
            in some cases it might lead to confusion with "【書：か】く". Better set interchangeable="false".
        -->
        <xs:attribute name="interchangeable" type="xs:boolean" />

        <!--
            Remark, ignored by the app.
        -->
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="AskAccept">
        <xs:attribute name="w" type="xs:string" use="required" />
        <xs:attribute name="suffix" type="xs:string" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        This is the root of the XML document.
    -->
    <xs:element name="vocabulary">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="topic" type="Topic" />
                <xs:element name="subheader" type="TopicSubheader" />
                <xs:element name="unit" type="Unyt" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== digorydoo/goigoi/goigoi-xml/voc_ja/040_n2/055_n2_verbs_3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="N2 verbs ③"
      name_de="N2-Verben ③"
      name_fr="Les verbes N2 ③"
      name_it="Verbi N2 ③"
      hasRomaji="true"
      hasFurigana="true"
      defaultHint_en="verb"
      defaultHint_de="Verb"
      lvl="n2"
      requiresSentences="false"
      requiresPhrases="false"
    >
        <section>
            <!-- unsorted -->
            <word
              w="【張：は】り【切：き】る"
              rom="hari-kiru"
              tr_en="to be enthusiastic; to be in high spirits"
              tr_de="enthusiastisch sein; in gehobener Stimmung sein"
              Langenscheidt="-"
              lvl="n2"
              id="harikiru-highspirits"
              rem="appears in 500mon N3 q38 (no example); appears in Doraemon 17, p.152"
            >
                <keep_apart_from id="isshōkenmei-utmosteffort" />
                <keep_apart_from id="omoikiri-withallstrength" />
                <!--
                    Can it mean to stretch to breaking point / bis zum Äussersten strapazieren ?
                -->
                <sentence
                  s="はりきって【歌：うた】うぞ！"
                  rom="Hari-kitte utau zo!"
                  tr_en="I'm going to sing my heart out!"
                  tr_de="Ich werden mit ganzem Elan singen!"
                  lvl="n2"
                  origin="Doraemon 17, p.152"
                >
                    <ask w="はりきって" />
                </sentence>
            </word>
            <word
              w="【解：ほど】く"
              rom="hodoku"
              tr_en="to undo; to untie; to unfasten"
              tr_de="lösen; aufbinden; entwirren"
              hint_en="v.t."
              lvl="n2"
              id="hodoku-undo"
            />
            <word
              w="【心：こころ】【得：え】る"
              rom="kokoroeru"
              tr_en="to know; to understand; to be aware of"
              tr_de="wissen; verstehen; sich etw. bewusst sein"
              hint_en="v.t."
              lvl="n2"
              id="kokoroeru-know"
            />
            <word
              w="【診：み】る"
              rom="miru"
              tr_en="to examine (medically)"
              tr_de="(medizinisch) untersuchen"
              hint_en="v.t."
              lvl="n2"
              category="health, looking"
              id="miru-examine"
            />
            <word
              w="【引：ひ】っ【込：こ】む"
              rom="hikkomu"
              tr_en="to draw back; to retire to (somewhere); to stay indoors"
              tr_de="sich zurückziehen; drinnen bleiben"
              hint_en="v.i."
              lvl="n2"
              id="hikkomu-drawback"
            />
            <word
              w="【受：う】け【持：も】つ"
              rom="ukemotsu"
              tr_en="to take charge of; to be in charge of"
              tr_de="sich um etw. kümmern; für etw. zuständig sein"
              hint_en="v.t."
              lvl="n2"
              id="ukemotsu-takechargeof"
            />
            <word
              w="【憧：あこが】れる"
              rom="akogareru"
              tr_en="to long for; to yearn after; to be attracted by"
              tr_de="sich nach etw. sehnen; nach etw. verlangen; von etw. angezogen sein"
              hint_en="v.i."
              lvl="n2"
              id="akogareru-longfor"
            />
            <word
              w="【転：ころ】がす"
              rom="korogasu"
              tr_en="to roll; to tip over"
              tr_de="etw. rollen lassen; etw. umkippen"
              hint_en="v.t."
              lvl="n2"
              id="korogasu-roll"
            />
            <word
              w="【溢：あふ】れる"
              rom="afureru"
              tr_en="to overflow; to brim over; to flood"
              tr_de="überschwappen; übervoll werden; überschwemmt werden"
              hint_en="v.i."
              lvl="n2"
              id="afureru-overflow"
            />
            <word
              w="【巫：ふ】【山：ざ】【戯：け】る"
              rom="fuzakeru"
              tr_en="to joke; to make fun of; to laugh at"
              tr_de="witzeln; sich über etw. oder jem. lustig machen"
              usuallyInKana="true"
              lvl="n2"
              id="fuzakeru-joke"
            />
            <word
              w="【囁：ささや】く"
              rom="sasayaku"
              tr_en="to whisper"
              tr_de="flüstern"
              lvl="n2"
              usuallyInKana="true"
              category="talking"
              id="sasayaku-whisper"
            />
            <word
              w="【思：おも】い【込：こ】む"
              rom="omoikomu"
              tr_en="to assume; to be determined (to do); to think obsessively (about)"
              tr_de="annehmen; entschieden sein (etw. zu tun)"
              hint_en="v.i."
              lvl="n2"
              id="omoikomu-assume"
            />
            <word
              w="【透：す】き【通：とお】る"
              rom="sukitōru"
              tr_en="to be transparent; to be clear"
              tr_de="transparent sein; klar sein"
              hint_en="v.i."
              lvl="n2"
              id="sukitōru-transparent"
            />
            <word
              w="【目：め】【立：だ】つ"
              rom="medatsu"
              tr_en="to be conspicuous; to stand out"
              tr_de="auffällig sein; auffallen"
              hint_en="v.i."
              lvl="n2"
              id="medatsu-standout"
            />
            <word
              w="【掘：ほ】る"
              rom="horu"
              tr_en="to dig; to excavate"
              tr_de="graben; ausgraben"
              lvl="n2"
              category="diy, garden"
              id="horu-todig"
            />
            <word
              w="【越：こ】える"
              rom="koeru"
              tr_en="to cross over; to pass through; to go past"
              tr_de="überqueren; durchkommen; hindurch gehen"
              hint_en="v.t."
              lvl="n2"
              id="koeru-crossover"
            >
                <keep_apart_from id="hei-fence" rem="ambiguity in phrases" />
            </word>
            <word
              w="【砕：くだ】ける"
              rom="kudakeru"
              tr_en="to break (into pieces); to be broken; to crumble"
              tr_de="(in Stücke) zerbrechen; bersten; kaputt sein"
              hint_en="v.i."
              lvl="n2"
              id="kudakeru-break"
            />
            <word
              w="しゃがむ"
              rom="shagamu"
              tr_en="to squat; to crouch"
              tr_de="kauern; hocken"
              hint_en="v.i."
              lvl="n2"
              id="shagamu-squat"
            />
            <word
              w="【草臥：くたび】れる"
              rom="kutabireru"
              tr_en="to be exhausted"
              tr_de="erschöpft sein"
              hasCombinedReading="true"
              lvl="n2"
              category="mood"
              id="kutabireru-exhausted"
              rem="appears in Doraemon 13, p.184 (not usable as example)"
            />
            <word
              w="【生：な】る"
              rom="naru"
              tr_en="to bear fruit"
              tr_de="Früchte tragen"
              hint_en="v.i."
              lvl="n2"
              id="naru-bearfruit"
            />
            <word
              w="【削：けず】る"
              rom="kezuru"
              tr_en="to shave (wood); to sharpen (pencil); to cut down (budget)"
              tr_de="(Holz) hobeln; (Bleistift) spitzen; (Budget) kürzen"
              hint_en="v.t."
              lvl="n2"
              id="kezuru-shave"
            />
            <word
              w="【言：こと】【付：づ】ける"
              rom="kotodzukeru"
              tr_en="to have someone send sth.; to use as an excuse"
              tr_de="etw. via jem. anderen schicken lassen; etw. als Ausrede verwenden"
              hint_en="v.t."
              lvl="n2"
              id="kotodzukeru-havesbsend"
            />
            <word
              w="【呆：あき】れる"
              rom="akireru"
              tr_en="to be amazed; to be shocked; to be disgusted"
              tr_de="erstaunt sein; schockiert sein; angewidert sein"
              lvl="n2"
              category="mood"
              id="akireru-amazed"
            />
            <word
              w="【擦：こす】る"
              rom="kosuru"
              tr_en="to rub; to scrub; to scrape"
              tr_de="reiben; schrubben; schaben"
              hint_en="v.t."
              lvl="n2"
              usuallyInKana="true"
              id="kosuru-rub"
            />
            <word
              w="【存：ぞん】じる"
              rom="zonjiru"
              tr_en="to think; to feel; to consider"
              tr_de="denken; fühlen; in Betracht ziehen"
              lvl="n2"
              rem="appears in 500mon q393; but as a polite form of shiru..."
              id="zonjiru-think"
            />
        </section>
    </unit>
</vocabulary>

=== digorydoo/goigoi/goigoi-xml/voc_ja/060_nx/960_nx_chinese_zodiac.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="Chinese zodiac"
      name_de="Chinesischer Tierkreis"
      name_fr="Le zodiaque chinois"
      name_it="Lo zodiaco cinese"
      lvl="-"
      hasRomaji="true"
      hasFurigana="true"
      requiresSentences="false"
      requiresPhrases="false"
    >
        <section>
            <word
              w="【子：ね】"
              rom="ne"
              tr_en="The Rat (zodiac)"
              tr_de="Ratte (Tierzeichen)"
              lvl="-"
              id="ne-rat"
            >
                <see id="nezumi-mouse" type="closely related" />
            </word>
            <word
              w="【丑：うし】"
              rom="ushi"
              tr_en="The Ox (zodiac)"
              tr_de="Büffel (Tierzeichen)"
              lvl="-"
              id="ushi-zodiac"
            >
                <see id="ushi-cow" type="closely related" />
            </word>
            <word
              w="【寅：とら】"
              rom="tora"
              tr_en="The Tiger (zodiac)"
              tr_de="Tiger (Tierzeichen)"
              lvl="-"
              id="tora-zodiac"
            >
                <see id="tora-tiger" type="closely related" />
            </word>
            <word
              w="【卯：う】"
              rom="u"
              tr_en="The Hare (zodiac)"
              tr_de="Hase (Tierzeichen)"
              lvl="-"
              id="u-hare"
            >
                <see id="usagi-rabbit" type="closely related" />
            </word>
            <word
              w="【辰：たつ】"
              rom="tatsu"
              tr_en="The Dragon (zodiac)"
              tr_de="Drache (Tierzeichen)"
              lvl="-"
              id="tatsu-zodiac"
            >
                <see id="ryū-dragon" type="closely related" />
            </word>
            <word
              w="【巳：み】"
              rom="mi"
              tr_en="The Serpent (zodiac)"
              tr_de="Schlange (Tierzeichen)"
              lvl="-"
              id="mi-zodiac"
            >
                <see id="hebi-snake" type="closely related" />
            </word>
            <word
              w="【午：うま】"
              rom="uma"
              tr_en="The Horse (zodiac)"
              tr_de="Pferd (Tierzeichen)"
              lvl="-"
              id="uma-zodiac"
            >
                <see id="uma-horse" type="closely related" />
            </word>
            <word
              w="【未：ひつじ】"
              rom="hitsuji"
              tr_en="The Ram (zodiac)"
              tr_de="Schaf (Tierzeichen)"
              lvl="-"
              id="hitsuji-zodiac"
            >
                <see id="hitsuji-sheep" type="closely related" />
            </word>
            <word
              w="【申：さる】"
              rom="saru"
              tr_en="The Monkey (zodiac)"
              tr_de="Affe (Tierzeichen)"
              lvl="-"
              id="saru-zodiac"
            >
                <see id="saru-monkey" type="closely related" />
            </word>
            <word
              w="【酉：とり】"
              rom="tori"
              tr_en="The Bird (zodiac)"
              tr_de="Hahn (Tierzeichen)"
              lvl="-"
              id="tori-zodiac"
            >
                <see id="tori-bird" type="closely related" />
            </word>
            <word
              w="【戌：いぬ】"
              rom="inu"
              tr_en="The Dog (zodiac)"
              tr_de="Hund (Tierzeichen)"
              lvl="-"
              id="inu-zodiac"
            >
                <see id="inu-dog" type="closely related" />
            </word>
            <word
              w="【亥：い】"
              rom="i"
              tr_en="The Boar (zodiac)"
              tr_de="Schwein (Tierzeichen)"
              lvl="-"
              id="i-boar"
            >
                <see id="buta-pig" type="closely related" />
            </word>
        </section>
    </unit>
</vocabulary>
