=== digorydoo/goigoi/goigoi-xml/schema/vocab_schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        JLPT level associated with this item. The value "-" explicitly states the item is not associated with any
        particular JLPT level.
    -->
    <xs:simpleType name="JLPTLevel">
        <xs:restriction base="xs:string">
            <xs:enumeration value="n5" />
            <xs:enumeration value="n4" />
            <xs:enumeration value="n3" />
            <xs:enumeration value="n2" />
            <xs:enumeration value="n1" />
            <xs:enumeration value="-" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Comma-separated list of JLPT levels.
    -->
    <xs:simpleType name="JLPTLevelList">
        <!--
            xs:list itemType="JLPTLevel" doesn't work, because we want a comma-separated list, which reads better
        -->
        <xs:restriction base="xs:string">
            <xs:pattern value="-|n[1-5](,\s*(-|n[1-5]))*" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        Tells whether the word should be studied in context rather than on its own.
        Typically used for abstract words whose descriptions are rather hard to grasp.
    -->
    <xs:simpleType name="StudyInContext">
        <xs:restriction base="xs:string">
            <xs:enumeration value="preferred" />
            <xs:enumeration value="required" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        The topic divides the entire vocabulary into large sections. There should only be a few.
    -->
    <xs:complexType name="Topic">
        <xs:attribute name="name_ja" type="xs:string" use="required" />
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="notice_en" type="xs:string" use="required" />
        <xs:attribute name="imgSrc" type="xs:string" />
        <xs:attribute name="bgColour" type="xs:string" />
        <xs:attribute name="linkText" type="xs:string" />
        <xs:attribute name="linkHref" type="xs:string" />
    </xs:complexType>

    <!--
        The unyts of a topic can be grouped by putting a subheader before each group of unyts.
    -->
    <xs:complexType name="TopicSubheader">
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" use="required" />
        <xs:attribute name="name_fr" type="xs:string" use="required" />
        <xs:attribute name="name_it" type="xs:string" use="required" />
    </xs:complexType>

    <!--
        A unyt is a lesson. It's called unyt and not unit to avoid confusion with Kotlin type Unit.
    -->
    <xs:complexType name="Unyt">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="section" type="UnytSection" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" use="required" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
        <xs:attribute name="hasRomaji" type="xs:boolean" use="required" />
        <xs:attribute name="hasFurigana" type="xs:boolean" use="required" />
        <xs:attribute name="defaultHint_en" type="xs:string" />
        <xs:attribute name="defaultHint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevelList" use="required" />
        <xs:attribute name="requiresSentences" type="xs:boolean" />
        <xs:attribute name="requiresPhrases" type="xs:boolean" />
        <xs:attribute name="ignoresCombinedReadings" type="xs:boolean" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />
    </xs:complexType>

    <!--
        The words of a unyt can be grouped by wrapping them into sections.
        If there is only one section in a unyt, it can be anonymous, otherwise at least name_en is required.
    -->
    <xs:complexType name="UnytSection">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="word" type="Word" />
        </xs:choice>
        <xs:attribute name="name_en" type="xs:string" />
        <xs:attribute name="name_de" type="xs:string" />
        <xs:attribute name="name_fr" type="xs:string" />
        <xs:attribute name="name_it" type="xs:string" />
    </xs:complexType>

    <!--
        A word in the vocabulary inside a particular unyt.
    -->
    <xs:complexType name="Word">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="phrase" type="Phrase" />
            <xs:element name="sentence" type="Sentence" />
            <xs:element name="keep_apart_from" type="KeepApartFrom" />
            <xs:element name="keep_together" type="KeepTogether" />
            <xs:element name="see" type="SeeAlso" />
            <xs:element name="accept_for_translation" type="WordAcceptForTranslation" />
        </xs:choice>

        <!--
            The word is defined with the `w` attribute. If the word has kana, we need to provide furigana. The furigana
            also defines the kana reading. The place where the okurigana is put matters: If it is put outside the
            furigana, it becomes actual okurigana, but if it is put inside the furigana, it becomes mere pronounciation.
            For instance, "【取：と】り【上：あ】げる" and "【取：とり】【上：あ】げる" both define the kana as "とりあげる", but
            the kanji rendering of the former is "取り上げる" (with okurigana), while the kanji rendering of the latter
            is "取上げる" (without okurigana). We usually use the most common rendering as the `w` parameter and mark
            other acceptable forms with <accept_for_translation>.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="Langenscheidt" type="xs:string" />
        <xs:attribute name="hint_en" type="xs:string" />
        <xs:attribute name="hint_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="dict" type="xs:string" />
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="usuallyInKana" type="xs:boolean" />
        <xs:attribute name="hasCombinedReading" type="xs:boolean" />
        <xs:attribute name="common" type="xs:boolean" />
        <xs:attribute name="studyInContext" type="StudyInContext" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
        <xs:attribute name="HIDDEN" type="xs:boolean" />

        <!--
            The category is restricted, see enum class WordCategory.
            We don't use xs:enumeration/xs:list here, because unfortunately, members of xs:list are separated by
            whitespace only, which reads very confusingly, e.g. "old-fashioned plant" instead of "old-fashioned, plant".
        -->
        <xs:attribute name="category" type="xs:string" />
    </xs:complexType>

    <!--
        Phrases are short, usually not full sentences, and never end with a punctuation character.
    -->
    <xs:complexType name="Phrase">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="ph" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Sentences are longer than phrases, should be full sentences, and must end with a punctuation character.
    -->
    <xs:complexType name="Sentence">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="ask" type="Ask" />
        </xs:choice>

        <xs:attribute name="s" type="xs:string" use="required" />
        <xs:attribute name="rom" type="xs:string" use="required" />
        <xs:attribute name="tr_en" type="xs:string" use="required" />
        <xs:attribute name="tr_de" type="xs:string" />
        <xs:attribute name="explanation_en" type="xs:string" />
        <xs:attribute name="explanation_de" type="xs:string" />
        <xs:attribute name="lvl" type="JLPTLevel" use="required" />
        <xs:attribute name="allowSpaces" type="xs:boolean" />
        <xs:attribute name="origin" type="xs:string" />
        <xs:attribute name="href" type="xs:anyURI" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        When the word is used inside a phrase or sentence in a different form rather than its dictionary form, we need
        to declare how the App should ask about the word.
    -->
    <xs:complexType name="Ask">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="accept" type="AskAccept" />
        </xs:choice>

        <!-- Either "w" alone or both "stem" and "suffix" are required, but we cannot express this in XSD 1.0 -->
        <xs:attribute name="w" type="xs:string" />
        <xs:attribute name="stem" type="xs:string" />
        <xs:attribute name="suffix" type="xs:string" />
    </xs:complexType>

    <!--
        Marks a word as potentially confusing together with another word. These words should not be studied together,
        and they must appear in different unyts. We usually mark synonyms and almost synonyms with this, and sometimes
        words whose declared phrases become ambiguous when the user may enter either of them.
    -->
    <xs:complexType name="KeepApartFrom">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Marks words that should be studied together. If their JLPT levels match, they should also be kept in the same
        unyt. We use this mostly for hidden words that should not wander from another, non-hidden word that is
        essentially the same, such as 風呂 and お風呂.
    -->
    <xs:complexType name="KeepTogether">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        Adds a see-also link from this word to another.
    -->
    <xs:complexType name="SeeAlso">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="type" type="SeeAlsoType" use="required" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        The type of see-also link
    -->
    <xs:simpleType name="SeeAlsoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="adjective" />
            <xs:enumeration value="antonym" />
            <xs:enumeration value="closely related" />
            <xs:enumeration value="noun" />
            <xs:enumeration value="v.i." />
            <xs:enumeration value="v.t." />
            <xs:enumeration value="verb" />
        </xs:restriction>
    </xs:simpleType>

    <!--
        When the user is presented the translation of a word without the context of a phrase or sentence, we can add
        more acceptable answers.
    -->
    <xs:complexType name="WordAcceptForTranslation">
        <!--
            The attribute `w` takes furigana; both kanji/okurigana and kana parts become acceptable answers. For
            instance, if w="【入：い】り【口：ぐち】", we'd accept either 入り口 or いりぐち.
        -->
        <xs:attribute name="w" type="xs:string" use="required" />

        <!--
            Marks this variant as inaccurate. The app will not count this answer as wrong, but will encourage the user
            to use the expected answer instead.
        -->
        <xs:attribute name="inaccurate" type="xs:boolean" />

        <!--
            Marks this variant as always interchangable. If you set this to "true", the variant will also be allowed in
            phrases and sentences when they use the word in the exact form as it was defined. If the phrase or sentence
            uses the word in a slightly altered form (e.g. not in dictionary form if it's a verb), the variant is still
            not allowed, because the app cannot apply the form directly. In those cases, mark the acceptable answers
            with <accept> inside <ask>. On the other hand, if you set interchangable="false", the variant will never
            be allowed in phrases and sentences.

            If the word's kana reading and the variant's kana reading are the same, the variant is treated as an
            alternate spelling. In that case, specifying `interchangeable` is required. If the word's kanji/okurigana
            and the variant's kanji/okurigana are the same, the variant is treated as an alternate reading. In that
            case, too, specifying `interchangeable` is required. Otherwise, `interchangeable` is optional and defaults
            to "false".

            Examples: (i) Suppose the word is defined as w="【入：いり】【口：ぐち】", and an acceptable answer is defined
            as w="【入：い】り【口：ぐち】". The kana reading is いりぐち for both variants, so the app will treat this as an
            alternate spelling. Set interchangeable="true" to allow using this variant in phrases and sentences.

            (ii) Word defined as w="【早：はや】い", translation is "early; fast", acceptable for this translation is
            w="【速：はや】い", whose translation is "fast". The kana reading is はやい for both variants, and the app will
            treat this as an alternate spelling. However, the alternate spelling cannot be used in a phrase or sentence
            whose context makes it clear that the meaning is "early", not "fast". Set interchangeable="false".

            (iii) Word defined as w="【描：えが】く", translation is "to draw; to paint", acceptable answer is
            w="【描：か】く". The kanji/okurigana is 描く for both variants, so the app will treat this as an alternate
            reading. If the app asks the user to type their answer in kana given the translation "to draw; to paint",
            we'll accept かく. Using that reading in a phrase or sentence about "【描：えが】く" might be acceptable, but
            in some cases it might lead to confusion with "【書：か】く". Better set interchangeable="false".
        -->
        <xs:attribute name="interchangeable" type="xs:boolean" />

        <!--
            Remark, ignored by the app.
        -->
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="AskAccept">
        <xs:attribute name="w" type="xs:string" use="required" />
        <xs:attribute name="suffix" type="xs:string" />
        <xs:attribute name="rem" type="xs:string" />
    </xs:complexType>

    <!--
        This is the root of the XML document.
    -->
    <xs:element name="vocabulary">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="topic" type="Topic" />
                <xs:element name="subheader" type="TopicSubheader" />
                <xs:element name="unit" type="Unyt" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== digorydoo/goigoi/goigoi-xml/voc_ja/030_n3/970_n3_hidden_verbs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="Hidden N3 verbs"
      hasRomaji="true"
      hasFurigana="true"
      defaultHint_en="verb"
      defaultHint_de="Verb"
      lvl="n3"
      requiresSentences="false"
      requiresPhrases="false"
      HIDDEN="true"
    >
        <section>
            <!-- unsorted -->
            <word
              w="【収：おさ】める"
              rom="osameru"
              tr_en="to pay (fees); to bring to a close; to achieve (a result)"
              tr_de="(Gebühren) zahlen; beenden; (ein Resultat) erreichen"
              lvl="n3"
              category="work, finances"
              id="osameru-pay"
            >
                <keep_apart_from id="eru-earn" />
                <keep_apart_from id="shōjiru-yield" />
                <phrase
                  ph="【成：せい】【功：こう】を【収：おさ】める"
                  rom="seikō o osameru"
                  tr_en="to come out successful; to achieve success"
                  tr_de="erfolgreich sein; Erfolg haben"
                  lvl="n3"
                  origin="lib0"
                />
            </word>
            <word
              w="【扱：あつか】う"
              rom="atsukau"
              tr_en="to deal with (a person, problem); to operate (a machine)"
              tr_de="sich (einem Problem, einer Person) annehmen; (Maschine) bedienen"
              lvl="n3"
              category="work, technical"
              id="atsukau-dealwith"
            />
            <word
              w="【得：う】る"
              rom="uru"
              tr_en="to be able to; to acquire sth.; to gain"
              tr_de="etw. können; sich etw. aneignen; etw. gewinnen"
              hint_en="v.t."
              lvl="n3"
              category="work"
              id="uru-obtain"
            />
            <word
              w="【防：ふせ】ぐ"
              rom="fusegu"
              tr_en="to defend against; to protect against; to avert"
              tr_de="sich gegen etw. verteidigen; sich gegen etw. schützen; etw. abwenden"
              hint_en="v.t."
              lvl="n3"
              category="general, politics"
              id="fusegu-avert"
            />
            <word
              w="【解：と】ける"
              rom="tokeru"
              tr_en="to be solved; to come undone; (spell) to be broken"
              tr_de="gelöst sein; lose werden; (Bann) aufgehoben sein"
              hint_en="v.i."
              lvl="n3"
              category="general"
              id="tokeru-besolved"
            />
            <word
              w="【支：ささ】える"
              rom="sasaeru"
              tr_en="to support; to defend; to hold at bay"
              tr_de="etw. unterstützen; etw. verteidigen; etw. in Schach halten"
              hint_en="v.t."
              lvl="n3"
              category="general, politics"
              id="sasaeru-support"
            />
            <word
              w="【欠：か】ける"
              rom="kakeru"
              tr_en="to be damaged; to be lacking; to be missing"
              tr_de="beschädigt sein; fehlen"
              lvl="n3"
              category="not-good, technical"
              id="kakeru-damaged"
            />
            <word
              w="【遣：や】る"
              rom="yaru"
              tr_en="to give sth."
              tr_de="etw. geben"
              hint_en="to pets, plants, younger siblings, etc."
              hint_de="einem Tier, einer Pflanze, einem jüngeren Geschwister, usw."
              studyInContext="required"
              lvl="n3"
              category="animal, hands"
              id="yaru-give"
              usuallyInKana="true"
              HIDDEN="true"
            >
                <!-- implicit see-also link to yaru-undertake -->
            </word>
            <word
              w="【眺：なが】める"
              rom="nagameru"
              tr_en="to gaze at; to admire (the scenery); to contemplate (a painting)"
              tr_de="betrachten; (Landschaft) bewundern; (einem Gemälde) nachsinnen"
              hint_en="v.t."
              lvl="n3"
              category="looking"
              id="nagameru-gaze"
            />
            <word
              w="【受：う】かる"
              rom="ukaru"
              tr_en="to pass (examination)"
              hint_en="v.i."
              lvl="n3"
              id="ukaru-pass"
              rem="jisho has n1"
            >
                <see id="ukeru-receive" type="v.t." />
                <keep_apart_from id="gōkaku-passexam" />
            </word>
            <word
              w="【取：と】り【調：しら】べる"
              rom="tori-shiraberu"
              tr_en="to investigate; to examine"
              hint_en="v.t."
              lvl="n3"
              rem="jisho has n1"
              id="torishiraberu-investigate"
            >
                <keep_apart_from id="shiraberu-lookup" />
            </word>
            <word
              w="【預：あず】ける"
              rom="azukeru"
              tr_en="to put sth. in so.'s care; to leave sth. in so.'s keeping"
              tr_de="etw. jemandem anvertrauen"
              hint_en="v.t."
              lvl="n3"
              category="general, relationships"
              id="azukeru-putincare"
            >
                <see id="azukaru-keepincustody" type="closely related" />
                <keep_apart_from id="sewa-trouble" />
            </word>
            <word
              w="【及：およ】ぼす"
              rom="oyobosu"
              tr_en="to exert (influence); to cause (damage); to bring about (benefits)"
              tr_de="(Einfluss) ausüben; (Schaden) anrichten; (Nutzen) bringen"
              lvl="n3"
              category="general"
              id="oyobosu-cause"
            />
            <word
              w="【燃：も】える"
              rom="moeru"
              tr_en="to burn; to get fired up"
              hint_en="v.i."
              lvl="n3"
              id="moeru-burn"
            />
            <word
              w="【罰：ばっ】する"
              rom="bassuru"
              tr_en="to punish; to penalize; to penalise"
              hint_en="suru verb"
              lvl="n3"
              id="bassuru-punish"
            />
            <word
              w="【異：こと】なる"
              rom="kotonaru"
              tr_en="to differ; to be different; to diverge"
              hint_en="v.i."
              lvl="n3"
              id="kotonaru-differ"
            />
            <word
              w="【引：ひ】っ【張：ぱ】る"
              rom="hipparu"
              tr_en="to pull tight; to string (lines); to run (cable); to put on"
              hint_en="v.t."
              lvl="n3"
              id="hipparu-run"
            />
            <word
              w="【戦：たたか】う"
              rom="tatakau"
              tr_en="to wage war; to fight (with); to compete (against)"
              hint_en="v.i."
              lvl="n3"
              id="tatakau-fight"
            />
            <word
              w="【対：たい】する"
              rom="tai suru"
              tr_en="to face; to be facing; to be related to"
              hint_en="suru verb (special class)"
              lvl="n3"
              id="taisuru-face"
            />
            <word
              w="【達：たっ】する"
              rom="tassuru"
              id="tassuru-reach"
              tr_en="to reach; to get to; to arrive at"
              hint_en="suru verb (special class)"
              lvl="n3"
            />
            <word
              w="【断：ことわ】る"
              rom="kotowaru"
              tr_en="to refuse; to reject; to dismiss; to turn down; to decline / to inform; to give notice; to tell in advance / to ask leave; to excuse oneself (from)"
              hint_en="v.t."
              lvl="n3"
            >
                <!--
                お願いを断る - to turn down, reject a wish (ChatGPT)
                -->
            </word>
            <word
              w="【含：ふく】む"
              rom="fukumu"
              tr_en="to contain; to comprise; to have; to hold; to include; to embrace / to hold in the mouth / to bear in mind; to understand; to harbor (grudge, etc.); to harbour / to express (emotion, etc.); to imply"
              hint_en="v.t."
              lvl="n3"
            />
            <word
              w="【就：つ】く"
              rom="tsuku"
              tr_en="to take (seat, position, course, office, etc.); to assume; to be hired; to be employed / to ascend (the throne); to accede / to start (on a journey); to commence; to depart / to study (under teacher); to be an apprentice"
              hint_en="v.i."
              lvl="n3"
              id="tsuku-assume"
            />
            <word
              w="【積：つ】もる"
              rom="tsumoru"
              tr_en="to pile up; to accumulate / to estimate"
              hint_en="v.t. &amp; i."
              lvl="n3"
            />
            <word
              w="【雇：やと】う"
              rom="yatou"
              tr_en="to employ; to hire; to take on / to charter (a car, boat, etc.); to hire"
              hint_en="v.t."
              lvl="n3"
            />
        </section>
    </unit>
</vocabulary>

=== digorydoo/goigoi/goigoi-xml/voc_ja/050_n1/980_n1_hidden_counters.xml
<?xml version="1.0" encoding="UTF-8" ?>
<vocabulary
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../../schema/vocab_schema.xsd"
>
    <unit
      name_en="Hidden N1 Counters"
      name_de="N1 Zählwörter"
      name_fr="Les mots de compter N1"
      name_it="Parole da contare N1"
      hasRomaji="true"
      hasFurigana="true"
      lvl="n1"
      ignoresCombinedReadings="false"
      HIDDEN="true"
    >
        <section>
            <word
              w="【問：もん】"
              rom="mon"
              tr_en="counter for questions"
              tr_de="Zählwort für Fragen"
              lvl="n1"
              id="mon-questions"
            />

            <!-- HIDDEN -->
            <word
              w="【版：はん】"
              rom="han"
              tr_en="edition; version; printing; impression; implementation (e.g. software); editions of a publication"
              lvl="n1"
              id="han-edition"
              HIDDEN="true"
            />
            <word
              w="【等：とう】"
              rom="tō"
              tr_en="class; order; rank; et cetera; etc.; and the like; equal; iso-"
              lvl="n1"
              id="tō-rank"
              HIDDEN="true"
            />
            <word
              w="【膳：ぜん】"
              rom="zen"
              tr_en="small dining table; serving tray; serving; counter for bowlfuls of rice; counter for pairs of chopsticks"
              lvl="n1"
              id="zen-tray"
              HIDDEN="true"
            />
            <word
              w="【畳：じょう】"
              rom="jō"
              tr_en="tatami mat (esp. as a measure of room size, either 1.82 sqm or 1.54 sqm)"
              lvl="n1"
              id="jō-tatamimat"
              HIDDEN="true"
            />
            <word
              w="【振：ふ】り"
              rom="furi"
              tr_en="shake; wave; swinging; appearance; behaviour; pretense; counter for swords, blades, etc."
              lvl="n1"
              id="furi-swing"
              HIDDEN="true"
            />
            <word
              w="【柱：はしら】"
              rom="hashira"
              tr_en="pillar; post; support; prop; mainstay; counter for buddhas, gods, nobles"
              lvl="n1"
              id="hashira-buddhas"
              HIDDEN="true"
            />
            <!-- rōmaji not unique...
              w="【戸：こ】"
              rom="ko"
              tr_en="counter for houses, households, apartments, etc."
              lvl="n1"
              id="ko-houses"
              HIDDEN="true"
            -->
            <word
              w="【校：こう】"
              rom="kō"
              tr_en="school; proof (of a book, document, etc.); counter for proofs"
              lvl="n1"
              id="kō-proofs"
              HIDDEN="true"
            />
            <word
              w="【次：じ】"
              rom="ji"
              tr_en="next; hypo- (i.e. containing an element with low valence); order; sequence; time; times"
              lvl="n1"
              id="ji-next"
              HIDDEN="true"
            />
            <word
              w="【泊：はく】"
              rom="haku"
              tr_en="counter for nights of a stay; overnight stay; lodging"
              lvl="n1"
              id="haku-nights"
              HIDDEN="true"
            />
            <!-- section
              name_en="ヶ月: Month-long periods"
              name_de="ヶ月: Monate-lange Intervalle"
            -->
            <!--
                ヶ月 is n1
                いっかげつ
                ろっかげつ
                はっかげつ
                じゅっかげつ
                なんかげつ？
            -->
            <!-- /section -->
            <!-- section
              name_en="階: Floors, storeys"
              name_de="階: Stockwerke"
            -->
            <!-- jisho: 階 is N1, 階段 is N5, 二階建て is N4, nan-kai is nx -->
            <!--
                いっかい
                さんがい
                ろっかい
                はっかい
                じゅっかい
                なんがい？
            -->
            <!-- /section -->
        </section>
    </unit>
</vocabulary>
